algoritmo "semnome"
var
   A, B, C: Real
   Delta: Real
   
inicio
      Escreva ("ATENCAO! QUANDO NÃO SOUBER O VALOR DA LETRA, DIGITE O NUMERO 1")
      Escreva ("Qual o valor de A?: ")
      Leia (a)
      Escreva ("Qual o valor de B?: ")
      Leia (b)
      Escreva ("Qual o valor de C?: ")
      Leia (c)
      Delta <- ((b*b) - 4 * a * c)
      Escreval ("O valor de delta é: ", delta)
      
      
fimalgoritmo